### PR TITLE
Validate RHS Resolved Names and Separators

### LINKED ISSUE #35: Validate RHS Resolved Names and Separators
Implement these validations:
- Within a rule, the resolved names for all RHS symbols must be unique.
- The separator for a repetition rule must be a terminal. </br> </br>
Inside the validate() method of the SyntacticRhsValidator class, calls to new _validateResolvedNames() and _validateSeparator() methods could be placed.
From _validateResolvedNames(), self.syntacticSpec should be accessed to resolve names and check against duplicates, appending to self.errorList when necessary.
From _validateSeparator(), self.syntacticSpec should be accessed to verify separator fields of RepeatingSyntacticRules, appending to self.errorList when necessary.

### PR DESCRIPTION
**Pull request by michaelBanerjee**
feat: add _validateResolvedNames() and _validateSeparator()

Within a rule, the resolved names for all RHS symbols must be unique.
The separator for a repetition rule must be a terminal.

---
* Closes #35 
---

Co-authored-by: Michael Banerjee <michaelbanerjee10@gmail.com>

### CODE REVIEW

**Comment by michaelBanerjee** [comment]
@StoneyJackson this is ready for review

**Comment by StoneyJackson** [comment]
@michaelBanerjee @connor-a-francis 

I couldn't resolve the conflicts here.

I think this PR is trying to implement a validation/check in the component that controls the process of validating the syntactic section. It should be its own submodule. Then there should likely be a one line change to the controller that calls the submodule to do the check.

I suggest doing something like the following...

1. Copy/download the files containing your code to your local machine.
2. In your development environment, create a new branch based on the current reorg branch.
    ```
    git switch reorg
    git switch -c validate_rhs_resolved_names_and_separators
    git push -u origin validate_rhs_resolved_names_and_separators
    ```
3. Create new files to hold the new code in the new branch.
    ```
    touch path/to/validate_rhs_resolved_names.py
    touch path/to/validate_rhs_resolved_names_test.py
    touch path/to/validate_rhs_separators.py
    touch path/to/validate_rhs_separators_test.py
    ...
    ```
4. Copy your code into the new files.
5. Make the new branch work (./bin/test/units.bash)
6. Commit, push
7. Offer a PR from the new branch.
8. Close this PR.

**Comment by StoneyJackson** [comment]
In fact, I'll go ahead and close it.

**Comment by StoneyJackson** [comment]
I'll leave the branch for a while. If there is no progress by the start of next semester, this may have to be a "redo".

**Pull request closed without merging**
